[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['Shougo/vimproc.vim']
hook_add = '''
let g:unite_source_history_yank_enable =1
let g:unite_source_file_mru_limit = 200
nnoremap <silent> ,u :<C-u>Unite <CR>
nnoremap <silent> ,uf :<C-u>Unite file <CR>
nnoremap <silent> ,ub :<C-u>Unite buffer <CR>
nnoremap <silent> ,ug :<C-u>Unite grep <CR>

" http://qiita.com/joker1007/items/c8962f9325a5433dc50d
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts = '--nocolor --nogroup --column'
let g:unite_source_grep_recursive_opt = ''
let g:unite_source_grep_max_candidates = 200

" http://blog.monochromegane.com/blog/2013/09/18/ag-and-unite/
if executable('ag')
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
  let g:unite_source_grep_recursive_opt = ''
endif
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }
set laststatus=2
'''

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['godlygeek/tabular']
hook_add = '''
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1
syntax on
'''

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
hook_add = '''
syntax on
'''

[[plugins]]
repo = 'taichouchou2/vim-endwise'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_path = "$HOME/Dropbox/memo"
let g:memolist_unite = 1
let g:memolist_memo_suffix = "md"
let g:memolist_unite_option = "-auto-preview -start-insert"
nnoremap <silent> ,mn :<C-u>MemoNew <CR>
nnoremap <silent> ,ml :<C-u>Unite -auto-preview memolist<CR>
nnoremap <silent> ,mg :<C-u>Unite -auto-preview memogrep<CR>

let g:unite_source_alias_aliases = {
\   "memogrep" : {
\       "source" : "grep",
\       "args" : g:memolist_path,
\   },
\   "memolist" : {
\       "source" : "file",
\       "args" : g:memolist_path,
\   },
\}
call unite#custom#source('memolist', 'sorters', ['sorter_reverse'])
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized.git'
hook_add = '''
set background=dark
colorscheme solarized
syntax on
'''
