tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-versions"
tap "homebrew/cask"

tap "robotsandpencils/made"

# Packages
brew "git"
brew "git-lfs"
brew "gibo"
brew "imagemagick"
brew "openssl"
brew "rbenv"
brew "nodenv"
brew "pyenv"
brew "ruby-build"
brew "readline"
brew "autoconf"
brew "sqlite"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "zplug"
brew "vim"
brew "ag"
brew "hub"
brew "libxml2"
brew "graphviz"
brew "go"
brew "direnv"
brew "tree"
brew "yarn"
brew "peco"
brew "ghq"
brew "zplug"
brew "mas"
brew "ffmpeg"
brew "kotlin"
brew "jasper"
brew "netpbm"
brew "mysql"
brew "gradle"
brew "rename"
brew "tfenv"
brew "apktool"
brew "bundletool"
brew "broot"
brew "jq"
brew "git-delta"
brew "firebase-cli"
brew "starship"
brew "openapi-generator"
brew "robotsandpencils/made/xcodes"
brew "aria2"
brew "gh"
brew "awscli"

cask "session-manager-plugin"
cask "google-chrome"
cask "firefox"
cask "iterm2"
cask "bettertouchtool"
cask "appcleaner"
cask "google-drive"
cask "jetbrains-toolbox"
cask "slack"
cask "docker"
cask "1password"
cask "kindle"
cask "karabiner-elements"
cask "mysqlworkbench"
cask "unity-hub"
cask "android-sdk"
cask "android-platform-tools"
cask "visual-studio-code"
cask "ngrok"
cask "charles"
cask "google-cloud-sdk"
cask "raycast"
cask "figma"
cask "atok"
cask "devtoys"
cask "skitch"
cask "warp"
cask "arc"

mas "LINE", id: 539883307
mas "Todoist", id: 585829637
mas "Noizio", id: 928871589
mas "Microsoft Remote Desktop", id: 715768417
mas "Giphy Capture", id: 668208984
mas "Affinity Designer", id: 824171161
mas "The Unarchiver", id: 425424353
mas "AnDrop", id: 1452111498
