tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "heroku/brew"

# Packages
brew "git"
brew "git-lfs"
brew "gibo"
brew "imagemagick"
brew "openssl"
brew "rbenv"
brew "nodenv"
brew "pyenv"
brew "ruby-build"
brew "readline"
brew "autoconf"
brew "sqlite"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "vim"
brew "ag"
brew "hub"
brew "libxml2"
brew "graphviz"
brew "go"
brew "direnv"
brew "tree"
brew "yarn"
brew "peco"
brew "ghq"
brew "zplug"
brew "mas"
brew "ffmpeg"
brew "heroku"
brew "kotlin"
brew "gts"
brew "jasper"
brew "netpbm"
brew "mysql"
brew "gradle"
brew "haskell-stack"
brew "rename"
brew "swagger-codegen"
brew "tfenv"
brew "apktool"
brew "bundletool"
brew "broot"
brew "jq"
brew "git-delta"
brew "swiftlint"
brew "firebase-cli"

cask "adoptopenjdk8"
cask "adoptopenjdk13"
cask "google-chrome"
cask "firefox"
cask "iterm2"
cask "alfred"
cask "bettertouchtool"
cask "rescuetime"
cask "dropbox"
cask "appcleaner"
cask "google-backup-and-sync"
cask "jetbrains-toolbox"
cask "rescuetime"
cask "slack"
cask "docker"
cask "1password"
cask "kindle"
cask "send-to-kindle"
cask "karabiner-elements"
cask "sketch"
cask "trailer"
cask "vivaldi"
cask "mysqlworkbench"
cask "blender"
cask "unity-hub"
cask "android-sdk"
cask "android-platform-tools"
cask "visual-studio-code"
cask "ngrok"
cask "vlc"
cask "toggl-track"

mas "LINE", id: 539883307
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
mas "Todoist", id: 585829637
mas "Desktop Calendar Plus", id: 524688159
mas "Noizio", id: 928871589
mas "Microsoft Remote Desktop", id: 715768417
mas "Giphy Capture", id: 668208984
mas "Affinity Designer", id: 824171161
mas "Skitch", id: 425955336
mas "Amphetamine", id: 937984704
mas "The Unarchiver", id: 425424353
